In [1]:
# Numpy broadcasting 
import numpy as np
arr=np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [2]:
arr[1:5]=12

In [3]:
arr

array([ 0, 12, 12, 12, 12,  5,  6,  7,  8,  9, 10])

In [4]:
arr=np.arange(0,11)

In [5]:
slice_of_arr=arr[0:5]

In [6]:
slice_of_arr

array([0, 1, 2, 3, 4])

In [7]:
slice_of_arr[:]

array([0, 1, 2, 3, 4])

In [8]:
slice_of_arr[:]=99

In [9]:
slice_of_arr

array([99, 99, 99, 99, 99])

In [10]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [11]:
# array or matrix indexing
arr_2d=np.array([[5,10,15],[20,25,30],[35,40,45]])

In [12]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [13]:
arr_2d.shape

(3, 3)

In [14]:
arr_2d[0][2]

15

In [15]:
arr_2d[1,2]

30

In [16]:
arr_2d[1:,1:]

array([[25, 30],
       [40, 45]])

In [17]:
arr=np.arange(0,11)

In [18]:
arr>4

array([False, False, False, False, False,  True,  True,  True,  True,
        True,  True])

In [19]:
arr[arr>4]

array([ 5,  6,  7,  8,  9, 10])

In [20]:
# TASK: Use numpy to check how many rolls were greater than 2. For example if dice_rolls=[1,2,3] then the answer is 1.
# NOTE: Many different ways to do this! Your final answer should be an integer.
# MAKE SURE TO READ THE FULL INSTRUCTIONS ABOVE CAREFULLY, AS THE EVALUATION SCRIPT IS VERY STRICT.
# Link to Solution: https://gist.github.com/Pierian-Data/ea3121efac5dd3338c280ff10068f9c8

import numpy as np
dice_rolls = np.array([3, 1, 5, 2, 5, 1, 1, 5, 1, 4, 2, 1, 4, 5, 3, 4, 5, 2, 4, 2, 6, 6, 3, 6, 2, 3, 5, 6, 5])
count=0
for i in range(len(dice_rolls)):
    
    if dice_rolls[i]>2:
        count=count+1
    else:
        count=count
count

# total_rolls_over_two = # This should be a single integer

19