In [1]:
# The numpy.linspace() function returns number spaces evenly w.r.t interval
# Syntax np.linspace(Start, End, Number of sempels you want to genrate)
import numpy as np 
np.linspace(10,50,5)

array([10., 20., 30., 40., 50.])

In [2]:
# numpy identity matrix
# Function is use for identity matrix is eye()
# Syntax np.eye("Number of row and column")

import numpy as np 
x=np.eye(4,5)
y=np.eye(4)
print("x:",x)
print("   ")
print("y:",y)

x: [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]]
   
y: [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [3]:
# genrate a random number array
# function random.rand()
#syntax np.random.rand(row, column)

import numpy as np
np.random.rand(3,3)

array([[0.31468179, 0.55907533, 0.68391317],
       [0.47485457, 0.58692266, 0.58838881],
       [0.36403241, 0.21883945, 0.60529376]])

In [4]:
#Standard normal distribution
x=np.random.randn(3,3)
x

array([[ 1.09875405,  0.03362124, -1.86351595],
       [ 1.71052545,  0.73456023, -0.98138305],
       [ 0.2678185 , -0.90010516, -2.3893019 ]])

In [5]:
np.random.randint(0,101,(3,4))

array([[81, 85, 27, 28],
       [69, 69, 45, 12],
       [33, 61, 20, 15]])

In [6]:
# If we want to genrate any random number array once than we use following syntax
np.random.seed(42)
np.random.rand(3)

array([0.37454012, 0.95071431, 0.73199394])

In [7]:
import numpy as np
arr=np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
# Give a shape to the array
arr.reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [9]:
randarr=np.random.randint(0,101,10)
randarr

array([60, 20, 82, 86, 74, 74, 87, 99, 23,  2])

In [10]:
# Find a maximum number
randarr.max()

99